### ISSUE TITLE
Allow configuration of SSID & Password without flashing the firmware

### ISSUE THREAD

**Issue by PBrunot** [fablab-bergamo/rfid-arduino#9]
Once in a box usb port of ESP32 may not be easily accessible. Right now the configuration is in secrets.h as compile-time constants, so recompile+flash is needed. 

Ideas to solve the probem:
- Expose a Bluetooth device and allow writes to bluetooth characteristics with app like nRF connect. 
- Starting of soft AP with a web management interface (slow and not secured, no https). Not sure if it can run parallel with the rest of the system. 

Requires
- persistent storage on esp32 flash

To be investigated
- if bluetooth can be secured
- if there are good soft AP + webserver libraries (maintained). Probably not with https though...
- there is no physical user interface except the RFID tags (e.g. no config button to be held in boot-time). So probably the config interface shall be present all the time.

**Comment by valerionew** [comment]
This works amazing, we've tested it before:


https://github.com/tzapu/WiFiManager

**Comment by PBrunot** [comment]
Thanks, this library looks perfect indeed. I will try it soon.

**Comment by PBrunot** [comment]
Completed. 

When WiFi configuration fails at *boot-time*, the WiFi AP and portal is activated. ON LCD Screen, the IP address of the portal is shown. The AP name will be "ESP xxxxxx" depending on chip id. 

When WiFi fails during runtime, the board will try to reconnect to MQTT broker every 30s with saved settings. There is no automatic portal launch in this case, because it may be a temporary AP failure.

LCD example:
![image](https://github.com/fablab-bergamo/rfid-arduino/assets/6236243/f106ce9a-e67e-4324-b41a-23cbd003a096)

I tested with a real esp32s2 and a mobile phone. The web portal allows the user to perform following configuration:
- WiFi SSID and password (mandatory)
- Machine ID (mandatory) 
- MQTT Broker server (mandatory)
- MQTT Switch topic (for shelly , disabled if empty)

Configuration is saved in EEPROM on successfully AP join.

Configuration Portal has a timeout after a few minutes.

- In this degraded mode without AP configuration, the connected machine shall still be usable (provided the RFID whitelist and default configuration are fine in the board), but clearly the usage tracking will be lost.
